### ISSUE TITLE
After successfully build the 3d-pack, its not able to load, CUDA ERR 304

### ISSUE THREAD

**Issue by felixsoong0825** [MrForExample/ComfyUI-3D-Pack#313]
I can install both with ComfyUI Manager or semi-auto,

```
 [Comfy3D] Successfully downloaded required python cpp source files
 [Comfy3D] Successfully installed Comfy3D! Let's Accelerate!
```

but I still can not load it

```
Warn!: Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 82, in <module>
    from Unique3D.scripts.project_mesh import multiview_color_projection, multiview_color_projection_texture, get_cameras_list, get_orbit_cameras_list
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 99, in <module>
    pix2faces_renderer = Pix2FacesRenderer()
                         ^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 73, in __init__
    _warmup(self._glctx, device)
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 67, in _warmup
    dr.rasterize(glctx, pos, tri, resolution=[256, 256])
  File "D:\ComfyUI\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 310, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\torch\autograd\function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 246, in forward
    out, out_db = _get_plugin(gl=True).rasterize_fwd_gl(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]

Warn!: Cannot import D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]
### Loading: ComfyUI-Manager (V2.51)
### ComfyUI Revision: 2615 [c6812947] *DETACHED | Released on '2024-08-26'

```

Is there any other way to use 3D-Pack, I have even tried the old versions, but never successfully load it

**Comment by felixsoong0825** [comment]
If there's any solutions, I'll be appreciate

**Comment by jakechai** [comment]
Check the NVIDIA settings and the display driver.

**Comment by felixsoong0825** [comment]
> Check the NVIDIA settings and the display driver.

Thank you for your reply, I have tried to reinstall Nvidia driver, both studio version and gforce version, but it never works.

**Comment by MrForExample** [comment]
@felixsoong0825 It does look like a CUDA Toolkit mismatch, make sure you have [CUDA toolkit 12.1](https://developer.nvidia.com/cuda-12-1-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local) or [CUDA tookit 11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local) installed

And check [this guide](https://github.com/bycloudai/SwapCudaVersionWindows) to make sure your system switched the CUDA version to the one you just installed

And then it should work, let me know if there is any other problem 👍

**Comment by felixsoong0825** [comment]
![img_v3_02f3_425e8c1c-fac0-4655-bd93-d33fa6fe4bcg](https://github.com/user-attachments/assets/c6e48481-bbc9-46e4-870d-d994dab6ebf9)


> Check the NVIDIA settings and the display driver.
After several random attempts, I found out for a computer with more than one display mode, we need to select only NVIDIA GPU, otherwise this err will rise.

**Comment by fazeaction** [comment]
Not sure why I don't have those options in my nvidia control panel, so adding here my solution for that weird Cuda error 304. Basically the problem was that I have two GPUs (integrated + dedicated 4080). Python was using for some reason the OpenGL for the integrated GPU and creating that weird error. To remove that error you need to add, in the display settings graphics, the python.exe app and select the Nvidia as preferred GPU.

**Comment by pvp-by** [comment]
@fazeaction big tnx
As already mentioned, the issue indeed stemmed from the integrated GPU of the processor, which caused conflicts with the discrete RTX 4090. In error 304. However, I tested ALL possible solutions, reassembled under several variants of sg121, cu124, Python 3.11 and 3.12, as well as multiple versions of Torch 2.4, 2.41, and 2.51.

PS win after 3day ...

**Comment by juntoaxx** [comment]
@felixsoong0825 big tnx,
I worked on this every installation failed until this solution. It never crossed my mind. Thanks
