### ISSUE TITLE
Unable to load under WSL 2 in Win10 due to: RuntimeError: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]

### ISSUE THREAD

**Issue by rob-ack** [MrForExample/ComfyUI-3D-Pack#425]
I get the following error loading comfyui 3d pack under WSL 2 on Win 10 while WSLg is working and i can run CUDA applications too.

```
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-01-13 23:39:31.216
** Platform: Linux
** Python version: 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
** Python executable: /usr/bin/python3
** ComfyUI Path: /mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI
** User directory: /mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/user
** ComfyUI-Manager config path: /mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/user/default/ComfyUI-Manager/config.ini
** Log path: /mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/user/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/custom_nodes/rgthree-comfy
   3.0 seconds: /mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 12282 MB, total RAM 80350 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 SUPER : cudaMallocAsync
Using pytorch attention
[Prompt Server] web root: /mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/web
Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
NumExpr defaulting to 16 threads.
/usr/local/lib/python3.12/dist-packages/kiui/nn/__init__.py:31: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

/usr/local/lib/python3.12/dist-packages/kiui/nn/__init__.py:37: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_bwd

Warn!: xFormers is not available (Attention)
Warn!: /usr/local/lib/python3.12/dist-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(

MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
libEGL warning: egl: failed to create dri2 screen
Warn!: Traceback (most recent call last):
  File "/mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/nodes.py", line 2106, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/custom_nodes/comfyui-3d-pack/__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/custom_nodes/comfyui-3d-pack/nodes.py", line 82, in <module>
    from Unique3D.scripts.project_mesh import multiview_color_projection, multiview_color_projection_texture, get_cameras_list, get_orbit_cameras_list
  File "/mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/Unique3D/scripts/project_mesh.py", line 99, in <module>
    pix2faces_renderer = Pix2FacesRenderer()
                         ^^^^^^^^^^^^^^^^^^^
  File "/mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/Unique3D/scripts/project_mesh.py", line 73, in __init__
    _warmup(self._glctx, device)
  File "/mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/Unique3D/scripts/project_mesh.py", line 67, in _warmup
    dr.rasterize(glctx, pos, tri, resolution=[256, 256])
  File "/usr/local/lib/python3.12/dist-packages/nvdiffrast/torch/ops.py", line 317, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/nvdiffrast/torch/ops.py", line 253, in forward
    out, out_db = _get_plugin(gl=True).rasterize_fwd_gl(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]

Warn!: Cannot import /mnt/i/ComfyUI_windows_portable_nvidia/ComfyUI_windows_portable/ComfyUI/custom_nodes/comfyui-3d-pack module for custom nodes: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.548 seconds.
Prefix dict has been built successfully.
Word segmentation module jieba initialized.

PyTorch version 2.5.1 available.
```

I tried and checked many things but i am unable to resolve the issue for now.

Do you have an idea what the problem is here?
Pls Help and if you need more info let me know.

**Comment by iiiCpu** [comment]
Cuda error: `cudaErrorOperatingSystem = 304`
_This error indicates that an OS call failed._
https://github.com/microsoft/WSL/issues/7589

Seems like WSL is a no.

**Comment by iiiCpu** [comment]
Do you have any reason not to run ComfyUI directly under Windows itself?

**Comment by rob-ack** [comment]
No i do both but some py packages like 'piper' and/or some dependencies are not directly supported via pip under win.
Possibly i can get it to work in the future when i invest some time. 

**But i do use ComfyUI with 3d pack too under windows right now and it works great.**

[However i tried WSL too since NVIDIA stated lately that they want to support CUDA under WLS 2 and the have good Docs on that too.](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#).
And indeed i was also able to build and run CUDA sample apps under WSL so i was certian that it would work.
So i struggled with this error a lot and was unable to figure out the root of the error (not that much of a py or CUDA pro here anyways).

Maybe i have a misconfiguration which i have to resolve. Ill give it a try in the future and will update if i found something.

**Comment by iiiCpu** [comment]
Dude... You have a problem in `cudaGraphicsGLRegisterBuffer` function.

- ___host__​ cudaError_t [cudaGraphicsGLRegisterImage ](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__OPENGL.html#group__CUDART__OPENGL_1g0fd33bea77ca7b1e69d1619caf44214b)( cudaGraphicsResource** resource, GLuint image, GLenum target, unsigned int  flags )_

- Register an **OpenGL** texture or renderbuffer object.

Now, the link you gave, section [4.2. Features Not Yet Supported](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#features-not-yet-supported)

- Limitations: **OpenGL-CUDA** Interop is not yet supported.

- Impact: Applications relying on **OpenGL** will not work.

There's the only thing you can do at the moment: nothing.

**Comment by rob-ack** [comment]
Yea. This will help others having this too. Ill close the issue ticket now since the issue is not related to ComfyUI 3D Pack.
Thank you for the explanation and pinpoint to the docs.

**Comment by xhiroga** [comment]
OpenGL-CUDA interoperability limitations in WSL, but there's a workaround that doesn't require any environment variables or special configuration.

The fix is to modify the ComfyUI-3D-Pack code to use the CUDA rasterizer instead of the OpenGL rasterizer. Here's what to change:

1. In `Gen_3D_Modules/Unique3D/scripts/project_mesh.py`, modify the `Pix2FacesRenderer` class:
```python
class Pix2FacesRenderer:
  def __init__(self, device="cuda"):
      # Use CUDA rasterizer instead of OpenGL to avoid CUDA-OpenGL interop issues
      self._glctx = dr.RasterizeCudaContext()  # Remove output_db parameter
      self.device = device
      _warmup(self._glctx, device)
```

2. In the same file, around line 505, replace:
```python
if force_cuda_rast:
  glctx = dr.RasterizeCudaContext()
else:
  glctx = dr.RasterizeGLContext()
```

With:
```python
# Always use CUDA rasterizer to avoid OpenGL-CUDA interoperability issues
glctx = dr.RasterizeCudaContext()
```

After making these changes, ComfyUI-3D-Pack loads and works perfectly in WSL.
The key insight is that nvdiffrast offers both OpenGL and CUDA-based rasterizers, and for WSL environments, we need to use the CUDA-only version to avoid the interop limitations.')
